#!/bin/python3

import sys


s,t = input().strip().split(' ')
s,t = [int(s),int(t)]
a,b = input().strip().split(' ')
a,b = [int(a),int(b)]
m,n = input().strip().split(' ')
m,n = [int(m),int(n)]
apple = [int(apple_temp) for apple_temp in input().strip().split(' ')]
orange = [int(orange_temp) for orange_temp in input().strip().split(' ')]

apple= [a+x for x in apple]
orange = [b+x for x in orange]

c_a=c_b=0
for i in apple:
    if i in range(s,t+1):
        c_a+=1
for i in orange:
    if i in range(s,t+1):
        c_b+=1   
print(c_a)
print(c_b)
