#!/bin/python3

import sys

def migratoryBirds(n, ar):
    d={}
    for item in ar:
        if item in d.keys():
            d[item]+=1
        else:
            d[item]=1
    ans=max(d.items(),key=lambda x:x[1])
    return ans[0]

n = int(input().strip())
ar = list(map(int, input().strip().split(' ')))
result = migratoryBirds(n, ar)
print(result)
